# Jekyll
# https://jekyllrb-ja.github.io/docs/configuration/
timezone: Asia/Tokyo
encoding: UTF-8

future: false
show_drafts: false

#relative_permalinks: true
permalink: /blog/:year-:month-:day/:slug:output_ext

url: https://www.ndxbn.tokyo

# Plugins
# https://help.github.com/articles/configuring-jekyll-plugins/
# https://pages.github.com/versions/
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
    # not documented yet.
    # https://github.com/github/pages-gem/commit/0c79d7caf66bf209d08d3ee3829c217716a63479
  - jekyll-octicons

sass:
  style: compressed

# Plugins Config
## common
title: ndxbn.tokyo
description: ndxbn's personal web site
